FROM ubuntu:18.04

MAINTAINER CyberTrustAdmin "ctadmin@example.com"

RUN apt update -y && apt install -y python3 python3-dev python3-pip pkg-config libsystemd-dev nmap build-essential libpython3-dev libdbus-1-dev libglib2.0-dev libgirepository1.0-dev libcairo2-dev iproute2 tcpdump net-tools wget sudo

COPY ./component/requirements.txt /A16/requirements.txt

COPY config.ini ./A16/a16config.ini

WORKDIR /A16

RUN pip3 install -r requirements.txt

RUN wget https://raw.githubusercontent.com/vulnersCom/nmap-vulners/master/vulners.nse && mv vulners.nse /usr/share/nmap/scripts/

copy ./component /A16 

ENV LC_ALL=C.UTF-8
ENV LANG=C.UTF-8

ENTRYPOINT [ "python3" ]
CMD ["-u", "-m", "flask", "run", "--host=0.0.0.0"] 
